import assert from "node:assert/strict";
import fs from "node:fs";
import vm from "node:vm";
import ts from "typescript";

const source = fs.readFileSync(new URL("../src/lib/format.ts", import.meta.url), "utf8");
const { outputText } = ts.transpileModule(source, { compilerOptions: { target: ts.ScriptTarget.ES2020, module: ts.ModuleKind.CommonJS } });
const context = { exports: {}, Intl, BigInt, Number, String };
vm.runInNewContext(outputText, context);
const { decimalToMicro, formatCredits } = context.exports;
assert.equal(decimalToMicro("0.000001"), 1);
assert.equal(decimalToMicro("0.0023"), 2300);
assert.equal(decimalToMicro("10000"), 10000000000);
assert.equal(decimalToMicro("0.000001"), 1);
assert.equal(decimalToMicro("9007199254.740991"), Number.MAX_SAFE_INTEGER);
assert.throws(() => decimalToMicro("9007199254.740992"));
assert.throws(() => decimalToMicro("-1"));
assert.throws(() => decimalToMicro("0.0000001"));
assert.equal(formatCredits(2300), "0.0023 Credits");
assert.equal(formatCredits(-2300), "-0.0023 Credits");
console.log("Credits precision and negative-balance formatting passed.");
const wireSource = fs.readFileSync(new URL("../src/lib/credits-wire.ts", import.meta.url), "utf8");
const wire = { exports: {} };
vm.runInNewContext(ts.transpileModule(wireSource, { compilerOptions: { target: ts.ScriptTarget.ES2020, module: ts.ModuleKind.CommonJS } }).outputText, wire);
const { encodeCreditsJSON, decodeCreditsJSON } = wire.exports;
const encoded = encodeCreditsJSON({ unit: "CREDITS", quota_microcredits: 10000000, billing: { image_prices: [{ charged_microcredits: 1 }] } });
assert.equal(JSON.parse(encoded).quota_microcredits, "10000000");
assert.equal(decodeCreditsJSON(encoded).billing.image_prices[0].charged_microcredits, 1);
assert.throws(() => decodeCreditsJSON('{"used_microcredits":"9007199254740993"}'));
assert.throws(() => decodeCreditsJSON('{"used_microcredits":100}'));
assert.equal(formatCredits(1), "0.000001 Credits");
assert.equal(formatCredits(500000), "0.5 Credits");
console.log("Native Credits wire contract passed.");
assert.equal(context.exports.creditsInputValue(Number.MAX_SAFE_INTEGER), "9007199254.740991");
assert.equal(context.exports.decimalToMicro(context.exports.creditsInputValue(Number.MAX_SAFE_INTEGER)), Number.MAX_SAFE_INTEGER);
assert.equal(formatCredits(-1), "-0.000001 Credits");
